// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://fyagqhcjfuhtjoeqshwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5YWdxaGNqZnVodGpvZXFzaHdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMDEwOTksImV4cCI6MjA3MjY3NzA5OX0.b8-BTufObxnbCUaPO9SHeN4pQVJ6fHvTb1NYC1jFKVo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    flowType: 'pkce',
    detectSessionInUrl: true,
    persistSession: true,
  }
});