// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

export const SUPABASE_URL = "https://puvdhnuvawjcifabxhfy.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1dmRobnV2YXdqY2lmYWJ4aGZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyODEwMDgsImV4cCI6MjA3Mzg1NzAwOH0.LVquf05nSTPePrEzouv_iubuK2pn-JL0T9W0MuUNRJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    flowType: 'pkce',
    detectSessionInUrl: true,
    persistSession: true,
  }
});